#!/usr/bin/env bash
# This a script that:
# creates the file /var/run/myscript.pid containing its PID
# Display to infinity and beyond indefinetly
# Display I hate the kill command when recievins SIGTERM
# Display Y U no love me?! reciving SIGINT
# Delete the file created while recievins SIGTERM and SIGQUIT.
terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'terminator' SIGQUIT
done
