#!/usr/bin/env bash
# Display "To infinity and beyond indefinetly with sleep 2 and
# "I am invisible!!!" when receivind SIGTERM.
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
