#!/usr/bin/env bash
# Display the content of the current directory in a list format.
for file in *
do
	if [ ! -d "$file" ] && [[ "$file" != .* ]]; then
		name=$(echo "$file" | cut -d'-' -f2-)
		echo "$name"
	fi
done
